// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseChildren(arg1) {
  return window['go']['main']['App']['BrowseChildren'](arg1);
}

export function CallMethod(arg1) {
  return window['go']['main']['App']['CallMethod'](arg1);
}

export function ClearVariableNodeInspection() {
  return window['go']['main']['App']['ClearVariableNodeInspection']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DiscoverEndpoints(arg1) {
  return window['go']['main']['App']['DiscoverEndpoints'](arg1);
}

export function GetDiagnosticLogs() {
  return window['go']['main']['App']['GetDiagnosticLogs']();
}

export function GetMethodDetails(arg1) {
  return window['go']['main']['App']['GetMethodDetails'](arg1);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSessionSafety() {
  return window['go']['main']['App']['GetSessionSafety']();
}

export function GetSessionTrend(arg1) {
  return window['go']['main']['App']['GetSessionTrend'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function InspectVariableNode(arg1) {
  return window['go']['main']['App']['InspectVariableNode'](arg1);
}

export function PickClientCertificate() {
  return window['go']['main']['App']['PickClientCertificate']();
}

export function PickClientPrivateKey() {
  return window['go']['main']['App']['PickClientPrivateKey']();
}

export function RefreshVariableNodeValue(arg1) {
  return window['go']['main']['App']['RefreshVariableNodeValue'](arg1);
}

export function SaveSavedConnection(arg1) {
  return window['go']['main']['App']['SaveSavedConnection'](arg1);
}

export function SearchAddressSpace(arg1) {
  return window['go']['main']['App']['SearchAddressSpace'](arg1);
}

export function SetReadOnlyMode(arg1) {
  return window['go']['main']['App']['SetReadOnlyMode'](arg1);
}

export function UnwatchVariableNode(arg1) {
  return window['go']['main']['App']['UnwatchVariableNode'](arg1);
}

export function WatchVariableNode(arg1) {
  return window['go']['main']['App']['WatchVariableNode'](arg1);
}

export function WriteVariableNodeValue(arg1) {
  return window['go']['main']['App']['WriteVariableNodeValue'](arg1);
}
