// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {opcua} from '../models';
import {main} from '../models';

export function BrowseChildren(arg1:string):Promise<Array<opcua.AddressNode>>;

export function ClearVariableNodeInspection():Promise<void>;

export function Connect(arg1:main.ConnectionRequest):Promise<void>;

export function Disconnect():Promise<void>;

export function DiscoverEndpoints(arg1:string):Promise<Array<opcua.Endpoint>>;

export function GetDiagnosticLogs():Promise<Array<main.DiagnosticLogEntry>>;

export function GetWatchlist():Promise<Array<main.WatchlistRowView>>;

export function InspectVariableNode(arg1:opcua.AddressNode):Promise<void>;

export function UnwatchVariableNode(arg1:string):Promise<void>;

export function WatchVariableNode(arg1:opcua.AddressNode):Promise<void>;
