// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseChildren(arg1) {
  return window['go']['main']['App']['BrowseChildren'](arg1);
}

export function ClearVariableNodeInspection() {
  return window['go']['main']['App']['ClearVariableNodeInspection']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DiscoverEndpoints(arg1) {
  return window['go']['main']['App']['DiscoverEndpoints'](arg1);
}

export function GetDiagnosticLogs() {
  return window['go']['main']['App']['GetDiagnosticLogs']();
}

export function GetSessionTrend(arg1) {
  return window['go']['main']['App']['GetSessionTrend'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function InspectVariableNode(arg1) {
  return window['go']['main']['App']['InspectVariableNode'](arg1);
}

export function UnwatchVariableNode(arg1) {
  return window['go']['main']['App']['UnwatchVariableNode'](arg1);
}

export function WatchVariableNode(arg1) {
  return window['go']['main']['App']['WatchVariableNode'](arg1);
}
